### ISSUE TITLE
Possible error in SHOW CREATE TABLE

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-mysql-server#594]
SQLAlchemy says this:

```
/Users/erizocosmico/Library/Python/2.7/lib/python/site-packages/sqlalchemy/dialects/mysql/reflection.py:62: SAWarning: Unknown schema content: u'`ref_name` TEXT NOT NULL,'
  util.warn("Unknown schema content: %r" % line)
/Users/erizocosmico/Library/Python/2.7/lib/python/site-packages/sqlalchemy/dialects/mysql/reflection.py:62: SAWarning: Unknown schema content: u'`commit_hash` TEXT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
  util.warn("Unknown schema content: %r" % line)
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    repo_df = pd.read_sql_table("refs", con=conn)
  File "/Users/erizocosmico/Library/Python/2.7/lib/python/site-packages/pandas/io/sql.py", line 242, in read_sql_table
    raise ValueError("Table %s not found" % table_name)
ValueError: Table refs not found
```

It's possible we have some kind of error in our `SHOW CREATE TABLE` implementation.

Reproduction case:

```python
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine('mysql+pymysql://root@127.0.0.1:3306/gitbase')
with engine.connect() as conn:
    repo_df = pd.read_sql_table("refs", con=conn)
```

**Comment by kuba--** [comment]
This what this python test gives us:
```
SHOW VARIABLES LIKE 'sql_mode'
SHOW VARIABLES LIKE 'lower_case_table_names'
SELECT VERSION()
SELECT DATABASE()
SELECT @@transaction_isolation
show collation where `Charset` = 'utf8mb4' and `Collation` = 'utf8mb4_bin'
SELECT CAST('test plain returns' AS CHAR(60)) AS anon_1
SELECT CAST('test unicode returns' AS CHAR(60)) AS anon_1
ROLLBACK
SHOW FULL TABLES FROM `gitbase`
SHOW FULL TABLES FROM `gitbase`
SHOW CREATE TABLE `refs`
ROLLBACK
```

It can be also a bug in sqlalchemy reflection:
https://github.com/sqlalchemy/sqlalchemy/issues/1117

**Comment by erizocosmico** [comment]
But that bug was fixed... 10 years ago.

**Comment by kuba--** [comment]
I think it was closed in 2008 by some bot but added to the milestone in Nov 2018:
`sqlalchemy-bot added this to the 0.5.0 milestone on Nov 27, 2018`

**Comment by kuba--** [comment]
I dug into sqlalhemy reflection package and I found _the first_ (from many) issue.
The parses use following regex to match `create table` syntax:
`^CREATE (?:\w+ +)?TABLE +`(?P<name>(?:``|[^`])+)` +\($`
what requires a new line after first '('. In other words, instead of one liner we have to return:
```
CREATE TABLE `refs` (
`name` TEXT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

**Comment by kuba--** [comment]
Btw. here is a nice tool to play with: https://regex101.com

**Comment by kuba--** [comment]
Anyway, I also submitted an new issue for sqlalchemy: 
https://github.com/sqlalchemy/sqlalchemy/issues/4456

**Comment by kuba--** [comment]
@erizocosmico - maybe we can add the script to integration tests - WDYT?
```python
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine('mysql+pymysql://user:pass@127.0.0.1:3306/test')
with engine.connect() as conn:
    repo_df = pd.read_sql_table("mytable", con=conn)
    for table_name in repo_df.to_dict():
        print(table_name)
```
